/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.risc.server;

public class App {
    public String getGreeting() {
        return "Hello world from server.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
